name: funder
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 

  firebase_auth:
  cloud_firestore:
  firebase_storage:
  shared_preferences: ^0.5.1+2
  modal_progress_hud: ^0.1.3

  image_picker:


  flutter_screenutil: ^0.5.2
  image_picker:


  





dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login_logo.png
    - assets/namrapatel.png
    - assets/trip.png
    - assets/roommates.jpeg
    - assets/family.png
    - assets/childhoodhomies.jpeg
    - assets/lakersnation.jpeg
    - assets/sorority.jpeg
    - assets/dimelogo.png
    - assets/dimelogo1.png
    - assets/dimewhite.png
    - assets/seanmei.jpeg
    - assets/shehabsalem.jpeg
    - assets/taher.jpeg

  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/proxima-nova.ttf    
